use_augmentation: true
batch_size: 64
epochs: 1000
resize_shape: [128, 128]
initial_learning_rate: 0.0001
model_path: "model.h5"
ood_model_path: "ood_model.h5"
data_path: "/media/ml/data_ml/flowers_dataset/"
ood_data_path: "/media/ml/data_ml/openimage/train_c_small/"